### ISSUE TITLE
Object stores should accept non-object values

### ISSUE THREAD

**Issue by philipwalton** [dhoulb/shelving-mock-indexeddb#1]
I'm getting the following stack trace for an error when trying to add a non-object value to an object store. The error comes from the logic on [this line](https://github.com/dhoulb/shelving-mock-indexeddb/blob/master/lib/mock.js#L766):

```
DataError: IDBObjectStore.put(): value must be an object
    at IDBObjectStore.put (/Users/philipwalton/Projects/philipwalton/workbox/node_modules/shelving-mock-indexeddb/lib/mock.js:766:43)
    at IDBObjectStore.add (/Users/philipwalton/Projects/philipwalton/workbox/node_modules/shelving-mock-indexeddb/lib/mock.js:816:44)
```

But storing non-object values is supported when providing your own key argument (or when using a key generator via `{autoIncrement: true}`).

Here's a good summary of what configs allow for what types of values:
https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB#Structuring_the_database

**Comment by dhoulb** [comment]
Thanks! Great spot. I've adjusted the code and added a couple of extra tests to account for that. The 1.0.5 release fixes this issue.
