### ISSUE TITLE
IndexedDB should support Blob, Date, File, etc.

### ISSUE THREAD

**Issue by philipwalton** [dhoulb/shelving-mock-indexeddb#2]
The IndexedDB spec allows for any type supported by the structured clone algorithm:
https://www.w3.org/TR/IndexedDB/#value-construct
https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm

If you're willing to add support for all of these, that'd be great, but if you don't want to, maybe just supporting any object would be better than throwing an error for code that doesn't error when run in the browser (since this is a mocking library).

**Comment by dhoulb** [comment]
Hi Philip

Thanks for the feedback (and sorry about the slow reply).

I was wondering/struggling how to deal with this when I wrote the mock. Obviously a lot of the `Blob`/`File`/`FileList` etc type objects won't work in Node (I wrote this primarily for use in Jest), but explicitly supporting `Date` and `Set` would probably be very valuable for that too.

I definitely want it to borp if someone tries to store an object that would fail in the browser, so I think it's fair to just explicitly allow the types the structured clone algorithm allows (assuming they're defined). It'll just be a quick modification of the `clone()` function and some minor updating of error messages.

It's tempting to just use this module: https://www.npmjs.com/package/realistic-structured-clone — what do you think?

I'll make a note to make that change, but it might be a while before I get to it. Feel free to do a pull request if you've got availability!

Thanks
Dave

**Comment by dhoulb** [comment]
Also, you're running this in the browser? What's your use case? (Just curious!)

**Comment by philipwalton** [comment]
We're running this in node, but we're [emulating a Service Worker environment](https://github.com/GoogleChrome/workbox/blob/ed962bc/infra/testing/sw-env.js), so we're stubbing out things like `Blob` (meaning if you were to check for it in your code and store it literally, it should just work).

**Comment by dhoulb** [comment]
Thanks, I've added support for that now in the **1.0.6** release. `Blob` and `File` etc should now work as expected.
