### ISSUE TITLE
Should objectStoreNames be a DOMStringList?

### ISSUE THREAD

**Issue by gauntface** [dhoulb/shelving-mock-indexeddb#4]
At the moment objectStoreNames is an array instead of a "DOMStringList" meaning it's missing `contains()` 

https://www.w3.org/TR/2015/REC-IndexedDB-20150108/#widl-IDBDatabase-objectStoreNames

**Comment by gauntface** [comment]
I've got a "fix" here: https://github.com/philipwalton/shelving-mock-indexeddb/pull/1 happy to raise a PR against this repo if it looks good to you.

**Comment by dhoulb** [comment]
Thanks! Merged that in — Ideally I'd mock out DOMStringList too but who has the time! Haha.
