### ISSUE TITLE
Unsure if idb naming regex is valid

### ISSUE THREAD

**Issue by gauntface** [dhoulb/shelving-mock-indexeddb#5]
Running the following in Chrome and Firefox was successful:

```javascript
var request = indexedDB.open("idb-name-`!@#$%^&*()http://helloworld.com/");
request.onerror = function(event) {
  console.error('ERROR');
};
request.onsuccess = function(event) {
  console.log('Success');
};
```

This fails the validIdentifier check in the mock however:

```javascript
	// Is the supplied identified a valid identifier?
	const r_identifier = /^[a-z_][a-zA-Z0-9_\-\$]*$/;
	function validIdentifier(identifier)
	{
		if (typeof identifier === 'string' && identifier.match(r_identifier)) return true;
		else return false;
	}
```

Is there any info on where the naming enforcement came from? i.e. is this a v1.0 vs v2.0 difference? Or maybe a v1 spec change?

**Comment by dhoulb** [comment]
Apologies for the slow reply.

This RegExp isn't based on the spec, it's trying to be more restrictive than that. My thinking at the time was I'd want to catch places where I'd personally used odd characters in a database name? 

I think that's a reasonable choice but I'm open to changing it if you've got a need to use other characters?
