### ISSUE TITLE
Consider defining prototype methods

### ISSUE THREAD

**Issue by philipwalton** [dhoulb/shelving-mock-indexeddb#8]
This may not be something you're interested in doing (it seems like your style is to keep instance variables defined lexically within the constructor), but in case it is, I thought I'd report it anyway.

By defining object methods on the instance itself rather than on the prototype, you make common patterns of feature detection impossible.

For example, we provide an in-library polyfill for users on browsers that don't support IDB 2, and we feature detect that as follows:

```js
if (!('getAll' in IDBObjectStore.prototype)) {
  // Implement polyfill...
}
```

This works in browsers, but it doesn't work with this mocking library. Anyway, as I said, something to consider if you're interested in supporting this use case.

**Comment by dhoulb** [comment]
Yeah this is definitely a reasonable request.

I wrote it this way to hide the private variables for the classes — but I think symbol keys are fine for this (or just underscore-prefixed variables) while we wait for a private props proposal to land.

Main issue is it'd require a big rewrite that I don't have the time for right now. Happy to accept PRs but I'm going to close this for now but if I ever need to make major changes to this mock I'll probably change to prototype functions anyway (as this style is a pig to work with!)

I'd also accept a temporary PR that just adds fake functions to each class 😊

**Comment by philipwalton** [comment]
Totally understandable!

I took the time to make the updates in my fork, and I'd be happy to merge those back in if you're interested, but my fork also includes a fair amount of other changes (stylistic, etc.) that make it easier for me to debug, which you're probably not interested in...

Anyway, overall these mocks are super helpful for us, but we're also maintaining a fork and primarily fixing bugs over there, so if you'd rather we only report bugs on that repo (and leave you alone), we're happy to do that too :)
